### ISSUE TITLE
Building with VSCode + PlatformIO 4.0 extension gives error: "`.text' will not fit in region `iram1_0_seg'"

### ISSUE THREAD

**Issue by donkawechico** [stelgenhof/AiLight#57] opened 2019-08-01 07:26 UTC
**Issue Description:** 
After pulling latest AiLight (0.6.1-dev) and installing the PlatformIO extension for vscode (which apparently installs the latest PlatformIO 4.0 version), trying to run the "PlatformIO: Build" command fails with the error: 

> "`.text' will not fit in region `iram1_0_seg'"

**AiLight version:** 0.6.1-dev

**IDE:** VSCode 1.36.1 with latest PlatformIO extension

**PlatformIO version:** 4.0

**Verbose Build output**

**OS**: MacOS Mojave 10.14.5

> Processing prod-ota (platform: espressif8266@1.5.0; board: esp8285; framework: arduino)
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp8285.html
> PLATFORM: Espressif 8266 1.5.0 > Generic ESP8285 Module
> HARDWARE: ESP8266 80MHz, 80KB RAM, 423.98KB Flash
> PACKAGES: toolchain-xtensa 1.40802.0 (4.8.2), tool-esptool 1.409.0 (4.9), framework-arduinoespressif8266 1.20300.1 (2.3.0)
> Converting main.ino
> LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 29 compatible libraries
> Scanning dependencies...
> Dependency Graph
> |-- <ArduinoJson> 5.13.4
> |-- <AsyncMqttClient> 0.8.2
> |   |-- <ESPAsyncTCP> 1.2.0
> |   |   |-- <ESP8266WiFi> 1.0
> |-- <my92xx> 3.0.3 #a876387
> |-- <ESPAsyncTCP> 1.2.0
> |   |-- <ESP8266WiFi> 1.0
> |-- <ESP Async WebServer> 1.2.2
> |   |-- <ESPAsyncTCP> 1.2.0
> |   |   |-- <ESP8266WiFi> 1.0
> |   |-- <Hash> 1.0
> |   |-- <ESP8266WiFi> 1.0
> |   |-- <ArduinoJson> 5.13.4
> |-- <ESP8266WiFi> 1.0
> |-- <ESP8266mDNS>
> |   |-- <ESP8266WiFi> 1.0
> |-- <Hash> 1.0
> |-- <AiLight>
> |   |-- <my92xx> 3.0.3 #a876387
> |-- <EEPROM> 1.0
> |-- <Ticker> 1.0
> |-- <ArduinoOTA> 1.0
> |   |-- <ESP8266mDNS>
> |   |   |-- <ESP8266WiFi> 1.0
> |   |-- <ESP8266WiFi> 1.0
> before_build([".pio/build/prod-ota/src/main.ino.cpp.o"], ["src/main.ino.cpp"])
> /Users/<username>/code/AiLight/node_modules/.bin/gulp
> Archiving .pio/build/prod-ota/lib78e/libArduinoJson_ID64.a
> Indexing .pio/build/prod-ota/lib78e/libArduinoJson_ID64.a
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/ESP8266WiFi.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/ESP8266WiFiAP.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/ESP8266WiFiScan.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/WiFiClient.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/WiFiClientSecure.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/WiFiServer.cpp.o
> Compiling .pio/build/prod-ota/libd25/ESP8266WiFi/WiFiUdp.cpp.o
> Compiling .pio/build/prod-ota/lib9ef/ESPAsyncTCP_ID305/AsyncPrinter.cpp.o
> Compiling .pio/build/prod-ota/lib9ef/ESPAsyncTCP_ID305/ESPAsyncTCP.cpp.o
> Compiling .pio/build/prod-ota/lib9ef/ESPAsyncTCP_ID305/ESPAsyncTCPbuffer.cpp.o
> Compiling .pio/build/prod-ota/lib9ef/ESPAsyncTCP_ID305/SyncClient.cpp.o
> Compiling .pio/build/prod-ota/lib9ef/ESPAsyncTCP_ID305/tcp_axtls.c.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient.cpp.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/ConnAckPacket.cpp.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/PingRespPacket.cpp.o
> Archiving .pio/build/prod-ota/libd25/libESP8266WiFi.a
> Indexing .pio/build/prod-ota/libd25/libESP8266WiFi.a
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/PubAckPacket.cpp.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/PubCompPacket.cpp.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/PubRecPacket.cpp.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/PubRelPacket.cpp.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/PublishPacket.cpp.o
> Archiving .pio/build/prod-ota/lib9ef/libESPAsyncTCP_ID305.a
> Indexing .pio/build/prod-ota/lib9ef/libESPAsyncTCP_ID305.a
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/SubAckPacket.cpp.o
> Compiling .pio/build/prod-ota/lib7a2/AsyncMqttClient_ID346/AsyncMqttClient/Packets/UnsubAckPacket.cpp.o
> Compiling .pio/build/prod-ota/lib2aa/my92xx/my92xx.cpp.o
> Compiling .pio/build/prod-ota/libe1f/Hash/Hash.cpp.o
> Compiling .pio/build/prod-ota/libe1f/Hash/sha1/sha1.c.o
> Archiving .pio/build/prod-ota/lib2aa/libmy92xx.a
> Indexing .pio/build/prod-ota/lib2aa/libmy92xx.a
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/AsyncEventSource.cpp.o
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/AsyncWebSocket.cpp.o
> [00:09:15] Using gulpfile ~/code/AiLight/gulpfile.js
> [00:09:15] Starting 'default'...
> [00:09:16] Starting 'clean'...
> [00:09:16] Finished 'clean' after 6.64 ms
> [00:09:16] Starting 'scss'...
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/SPIFFSEditor.cpp.o
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/WebAuthentication.cpp.o
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/WebHandlers.cpp.o
> Archiving .pio/build/prod-ota/libe1f/libHash.a
> Indexing .pio/build/prod-ota/libe1f/libHash.a
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/WebRequest.cpp.o
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/WebResponses.cpp.o
> [00:09:16] Finished 'scss' after 299 ms
> [00:09:16] Starting 'base64CSS'...
> [00:09:16] Finished 'base64CSS' after 11 ms
> [00:09:16] Starting 'html'...
> Compiling .pio/build/prod-ota/lib63d/ESP Async WebServer_ID306/WebServer.cpp.o
> Compiling .pio/build/prod-ota/lib941/ESP8266mDNS/ESP8266mDNS.cpp.o
> Compiling .pio/build/prod-ota/lib36e/AiLight/AiLight.cpp.o
> Archiving .pio/build/prod-ota/lib36e/libAiLight.a
> Indexing .pio/build/prod-ota/lib36e/libAiLight.a
> Compiling .pio/build/prod-ota/lib86c/EEPROM/EEPROM.cpp.o
> Archiving .pio/build/prod-ota/lib86c/libEEPROM.a
> Indexing .pio/build/prod-ota/lib86c/libEEPROM.a
> Compiling .pio/build/prod-ota/lib6f4/Ticker/Ticker.cpp.o
> Archiving .pio/build/prod-ota/lib6f4/libTicker.a
> Indexing .pio/build/prod-ota/lib6f4/libTicker.a
> Compiling .pio/build/prod-ota/libdcf/ArduinoOTA/ArduinoOTA.cpp.o
> Archiving .pio/build/prod-ota/libFrameworkArduinoVariant.a
> Indexing .pio/build/prod-ota/libFrameworkArduinoVariant.a
> Compiling .pio/build/prod-ota/FrameworkArduino/Esp.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/FS.cpp.o
> Archiving .pio/build/prod-ota/lib7a2/libAsyncMqttClient_ID346.a
> Indexing .pio/build/prod-ota/lib7a2/libAsyncMqttClient_ID346.a
> Compiling .pio/build/prod-ota/FrameworkArduino/HardwareSerial.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/IPAddress.cpp.o
> Archiving .pio/build/prod-ota/lib63d/libESP Async WebServer_ID306.a
> Archiving .pio/build/prod-ota/lib941/libESP8266mDNS.a
> Indexing .pio/build/prod-ota/lib63d/libESP Async WebServer_ID306.a
> Indexing .pio/build/prod-ota/lib941/libESP8266mDNS.a
> Compiling .pio/build/prod-ota/FrameworkArduino/MD5Builder.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/Print.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/Schedule.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/Stream.cpp.o
> [00:09:17] Finished 'html' after 1.66 s
> [00:09:17] Starting 'header'...
> Compiling .pio/build/prod-ota/FrameworkArduino/StreamString.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/Tone.cpp.o
> [00:09:18] Finished 'header' after 170 ms
> [00:09:18] Finished 'default' after 2.15 s
> Compiling .pio/build/prod-ota/FrameworkArduino/Updater.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/WMath.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/WString.cpp.o
> Compiling .pio/build/prod-ota/src/main.ino.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/abi.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/base64.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/cbuf.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/cont.S.o
> Archiving .pio/build/prod-ota/libdcf/libArduinoOTA.a
> Indexing .pio/build/prod-ota/libdcf/libArduinoOTA.a
> Compiling .pio/build/prod-ota/FrameworkArduino/cont_util.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_eboot_command.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_flash_utils.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_i2s.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_main.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_noniso.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_phy.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_postmortem.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_si2c.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_timer.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_wiring.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_wiring_analog.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_wiring_digital.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_wiring_pulse.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_wiring_pwm.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/core_esp8266_wiring_shift.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/debug.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/heap.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/libb64/cdecode.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/libb64/cencode.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/libc_replacements.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/pgmspace.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/setjmp.S.o
> Compiling .pio/build/prod-ota/FrameworkArduino/spiffs/spiffs_cache.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/spiffs/spiffs_check.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/spiffs/spiffs_gc.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/spiffs/spiffs_hydrogen.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/spiffs/spiffs_nucleus.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/spiffs_api.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/spiffs_hal.cpp.o
> Compiling .pio/build/prod-ota/FrameworkArduino/time.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/uart.c.o
> Compiling .pio/build/prod-ota/FrameworkArduino/umm_malloc/umm_malloc.c.o
> Archiving .pio/build/prod-ota/libFrameworkArduino.a
> Indexing .pio/build/prod-ota/libFrameworkArduino.a
> Linking .pio/build/prod-ota/firmware.elf
> /Users/<username>/.platformio/packages/toolchain-xtensa@1.40802.0/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/prod-ota/firmware.elf section `.text' will not fit in region `iram1_0_seg'
> collect2: error: ld returned 1 exit status
> *** [.pio/build/prod-ota/firmware.elf] Error 1

**Comment by donkawechico** [comment] 2019-08-01 08:08
FWIW, I was able to work around this by:
1. Opening VSCode
2. Cmnd+Shift+P -> PlatformIO: New Terminal
3. In terminal: `pip2.7 uninstall platformio`
4. `pip2.7 install platformio==3.6.7`
5. Rerun the OTA command: `platformio run --target upload --environment "prod-ota" --upload-port=<hostname>`

**Comment by stelgenhof** [comment] 2019-08-01 13:21
Thanks! I am aware of this (Just didn't create an issue yet). The issue is indeed with PlatformIO rather than this firmware. To my understanding a fix was made but perhaps not released, so kind of waiting for that.

Your workaround is indeed good: rollback PlatformIO back to a stable version. Perhaps this is something I should enforce in the project.

Cheers! Sacha

**Comment by donkawechico** [comment] 2019-08-01 18:24
Hm. As of a couple weeks ago, this is considered a "wontfix" by PlatformIO: https://github.com/platformio/platformio-core/issues/2780

Comment explaining why: https://github.com/arendst/Sonoff-Tasmota/issues/6073#issuecomment-511109803

I see Tasmota has made some changes very recently to platformio.ini to support 4.0:
https://github.com/arendst/Sonoff-Tasmota/commits/development/platformio.ini

Perhaps all that's needed is to add the "build_dir" parameter to "[platformio]" config section?

I can give it a shot locally and report back.

**Comment by donkawechico** [comment] 2019-08-01 18:33
Well by golly, it worked! 

Snippit:
```
[platformio]
default_envs = prod-ota
build_dir = .pioenvs
```

I'll see if I can put up a PR real quick

**Comment by donkawechico** [comment] 2019-08-01 21:09
Here's the PR: https://github.com/stelgenhof/AiLight/pull/59. 

@stelgenhof, care to give it a shot and see if it builds for you under the latest PlatformIO?

FYI: I didn't check whether this breaks builds for older versions of PlatformIO, like 3.6.7.

**Comment by stelgenhof** [comment] 2019-08-02 13:51
Thanks! Merged your PR. Compiled it and works perfectly!

**Closed as completed by stelgenhof** 2019-08-02 13:51 UTC

**Comment by aHcVolle** [comment] 2019-10-17 16:49
FYI: ESP Async WebServer in version 1.2.3 breaks the build, with version 1.2.2 the build is still working fine

**Comment by stelgenhof** [comment] 2019-10-18 04:18
@aHcVolle Thanks for informing. Can you maybe create a separate issue for this?
